// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/gold_gym.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoldGymService_GetGoldUser_FullMethodName        = "/goldgym.GoldGymService/GetGoldUser"
	GoldGymService_GetGoldUserByEmail_FullMethodName = "/goldgym.GoldGymService/GetGoldUserByEmail"
	GoldGymService_LoginUser_FullMethodName          = "/goldgym.GoldGymService/LoginUser"
	GoldGymService_InsertGoldUser_FullMethodName     = "/goldgym.GoldGymService/InsertGoldUser"
	GoldGymService_GetAllSubscription_FullMethodName = "/goldgym.GoldGymService/GetAllSubscription"
)

// GoldGymServiceClient is the client API for GoldGymService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoldGymServiceClient interface {
	// GetGoldUser retrieves all gold gym users
	GetGoldUser(ctx context.Context, in *GetGoldUserRequest, opts ...grpc.CallOption) (*GetGoldUserResponse, error)
	// GetGoldUserByEmail retrieves a single user by email
	GetGoldUserByEmail(ctx context.Context, in *GetGoldUserByEmailRequest, opts ...grpc.CallOption) (*GetGoldUserByEmailResponse, error)
	// LoginUser authenticates a user and returns token
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	// InsertGoldUser creates a new user
	InsertGoldUser(ctx context.Context, in *InsertGoldUserRequest, opts ...grpc.CallOption) (*InsertGoldUserResponse, error)
	// GetAllSubscription retrieves all available subscriptions
	GetAllSubscription(ctx context.Context, in *GetAllSubscriptionRequest, opts ...grpc.CallOption) (*GetAllSubscriptionResponse, error)
}

type goldGymServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoldGymServiceClient(cc grpc.ClientConnInterface) GoldGymServiceClient {
	return &goldGymServiceClient{cc}
}

func (c *goldGymServiceClient) GetGoldUser(ctx context.Context, in *GetGoldUserRequest, opts ...grpc.CallOption) (*GetGoldUserResponse, error) {
	out := new(GetGoldUserResponse)
	err := c.cc.Invoke(ctx, GoldGymService_GetGoldUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldGymServiceClient) GetGoldUserByEmail(ctx context.Context, in *GetGoldUserByEmailRequest, opts ...grpc.CallOption) (*GetGoldUserByEmailResponse, error) {
	out := new(GetGoldUserByEmailResponse)
	err := c.cc.Invoke(ctx, GoldGymService_GetGoldUserByEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldGymServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, GoldGymService_LoginUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldGymServiceClient) InsertGoldUser(ctx context.Context, in *InsertGoldUserRequest, opts ...grpc.CallOption) (*InsertGoldUserResponse, error) {
	out := new(InsertGoldUserResponse)
	err := c.cc.Invoke(ctx, GoldGymService_InsertGoldUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldGymServiceClient) GetAllSubscription(ctx context.Context, in *GetAllSubscriptionRequest, opts ...grpc.CallOption) (*GetAllSubscriptionResponse, error) {
	out := new(GetAllSubscriptionResponse)
	err := c.cc.Invoke(ctx, GoldGymService_GetAllSubscription_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoldGymServiceServer is the server API for GoldGymService service.
// All implementations must embed UnimplementedGoldGymServiceServer
// for forward compatibility
type GoldGymServiceServer interface {
	// GetGoldUser retrieves all gold gym users
	GetGoldUser(context.Context, *GetGoldUserRequest) (*GetGoldUserResponse, error)
	// GetGoldUserByEmail retrieves a single user by email
	GetGoldUserByEmail(context.Context, *GetGoldUserByEmailRequest) (*GetGoldUserByEmailResponse, error)
	// LoginUser authenticates a user and returns token
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	// InsertGoldUser creates a new user
	InsertGoldUser(context.Context, *InsertGoldUserRequest) (*InsertGoldUserResponse, error)
	// GetAllSubscription retrieves all available subscriptions
	GetAllSubscription(context.Context, *GetAllSubscriptionRequest) (*GetAllSubscriptionResponse, error)
	mustEmbedUnimplementedGoldGymServiceServer()
}

// UnimplementedGoldGymServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoldGymServiceServer struct {
}

func (UnimplementedGoldGymServiceServer) GetGoldUser(context.Context, *GetGoldUserRequest) (*GetGoldUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoldUser not implemented")
}
func (UnimplementedGoldGymServiceServer) GetGoldUserByEmail(context.Context, *GetGoldUserByEmailRequest) (*GetGoldUserByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoldUserByEmail not implemented")
}
func (UnimplementedGoldGymServiceServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedGoldGymServiceServer) InsertGoldUser(context.Context, *InsertGoldUserRequest) (*InsertGoldUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertGoldUser not implemented")
}
func (UnimplementedGoldGymServiceServer) GetAllSubscription(context.Context, *GetAllSubscriptionRequest) (*GetAllSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSubscription not implemented")
}
func (UnimplementedGoldGymServiceServer) mustEmbedUnimplementedGoldGymServiceServer() {}

// UnsafeGoldGymServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoldGymServiceServer will
// result in compilation errors.
type UnsafeGoldGymServiceServer interface {
	mustEmbedUnimplementedGoldGymServiceServer()
}

func RegisterGoldGymServiceServer(s grpc.ServiceRegistrar, srv GoldGymServiceServer) {
	s.RegisterService(&GoldGymService_ServiceDesc, srv)
}

func _GoldGymService_GetGoldUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoldUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldGymServiceServer).GetGoldUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldGymService_GetGoldUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldGymServiceServer).GetGoldUser(ctx, req.(*GetGoldUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldGymService_GetGoldUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoldUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldGymServiceServer).GetGoldUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldGymService_GetGoldUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldGymServiceServer).GetGoldUserByEmail(ctx, req.(*GetGoldUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldGymService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldGymServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldGymService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldGymServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldGymService_InsertGoldUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertGoldUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldGymServiceServer).InsertGoldUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldGymService_InsertGoldUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldGymServiceServer).InsertGoldUser(ctx, req.(*InsertGoldUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoldGymService_GetAllSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldGymServiceServer).GetAllSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoldGymService_GetAllSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldGymServiceServer).GetAllSubscription(ctx, req.(*GetAllSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoldGymService_ServiceDesc is the grpc.ServiceDesc for GoldGymService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoldGymService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goldgym.GoldGymService",
	HandlerType: (*GoldGymServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoldUser",
			Handler:    _GoldGymService_GetGoldUser_Handler,
		},
		{
			MethodName: "GetGoldUserByEmail",
			Handler:    _GoldGymService_GetGoldUserByEmail_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _GoldGymService_LoginUser_Handler,
		},
		{
			MethodName: "InsertGoldUser",
			Handler:    _GoldGymService_InsertGoldUser_Handler,
		},
		{
			MethodName: "GetAllSubscription",
			Handler:    _GoldGymService_GetAllSubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gold_gym.proto",
}
