// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/gold_gym.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetGoldUserRequest is the request message for GetGoldUser RPC
type GetGoldUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoldUserRequest) Reset() {
	*x = GetGoldUserRequest{}
	mi := &file_proto_gold_gym_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoldUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoldUserRequest) ProtoMessage() {}

func (x *GetGoldUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoldUserRequest.ProtoReflect.Descriptor instead.
func (*GetGoldUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{0}
}

// GetGoldUserByEmailRequest is the request message for GetGoldUserByEmail RPC
type GetGoldUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoldUserByEmailRequest) Reset() {
	*x = GetGoldUserByEmailRequest{}
	mi := &file_proto_gold_gym_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoldUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoldUserByEmailRequest) ProtoMessage() {}

func (x *GetGoldUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoldUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetGoldUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoldUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// GoldUser represents a gold gym user entity
type GoldUser struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GoldId                int32                  `protobuf:"varint,1,opt,name=gold_id,json=goldId,proto3" json:"gold_id,omitempty"`
	GoldEmail             string                 `protobuf:"bytes,2,opt,name=gold_email,json=goldEmail,proto3" json:"gold_email,omitempty"`
	GoldPassword          string                 `protobuf:"bytes,3,opt,name=gold_password,json=goldPassword,proto3" json:"gold_password,omitempty"`
	GoldNama              string                 `protobuf:"bytes,4,opt,name=gold_nama,json=goldNama,proto3" json:"gold_nama,omitempty"`
	GoldNomorhp           string                 `protobuf:"bytes,5,opt,name=gold_nomorhp,json=goldNomorhp,proto3" json:"gold_nomorhp,omitempty"`
	GoldNomorkartu        string                 `protobuf:"bytes,6,opt,name=gold_nomorkartu,json=goldNomorkartu,proto3" json:"gold_nomorkartu,omitempty"`
	GoldCvv               string                 `protobuf:"bytes,7,opt,name=gold_cvv,json=goldCvv,proto3" json:"gold_cvv,omitempty"`
	GoldExpireddate       string                 `protobuf:"bytes,8,opt,name=gold_expireddate,json=goldExpireddate,proto3" json:"gold_expireddate,omitempty"`
	GoldNamapemegangkartu string                 `protobuf:"bytes,9,opt,name=gold_namapemegangkartu,json=goldNamapemegangkartu,proto3" json:"gold_namapemegangkartu,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GoldUser) Reset() {
	*x = GoldUser{}
	mi := &file_proto_gold_gym_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoldUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoldUser) ProtoMessage() {}

func (x *GoldUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoldUser.ProtoReflect.Descriptor instead.
func (*GoldUser) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{2}
}

func (x *GoldUser) GetGoldId() int32 {
	if x != nil {
		return x.GoldId
	}
	return 0
}

func (x *GoldUser) GetGoldEmail() string {
	if x != nil {
		return x.GoldEmail
	}
	return ""
}

func (x *GoldUser) GetGoldPassword() string {
	if x != nil {
		return x.GoldPassword
	}
	return ""
}

func (x *GoldUser) GetGoldNama() string {
	if x != nil {
		return x.GoldNama
	}
	return ""
}

func (x *GoldUser) GetGoldNomorhp() string {
	if x != nil {
		return x.GoldNomorhp
	}
	return ""
}

func (x *GoldUser) GetGoldNomorkartu() string {
	if x != nil {
		return x.GoldNomorkartu
	}
	return ""
}

func (x *GoldUser) GetGoldCvv() string {
	if x != nil {
		return x.GoldCvv
	}
	return ""
}

func (x *GoldUser) GetGoldExpireddate() string {
	if x != nil {
		return x.GoldExpireddate
	}
	return ""
}

func (x *GoldUser) GetGoldNamapemegangkartu() string {
	if x != nil {
		return x.GoldNamapemegangkartu
	}
	return ""
}

// GetGoldUserResponse is the response message for GetGoldUser RPC
type GetGoldUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GoldUser            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoldUserResponse) Reset() {
	*x = GetGoldUserResponse{}
	mi := &file_proto_gold_gym_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoldUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoldUserResponse) ProtoMessage() {}

func (x *GetGoldUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoldUserResponse.ProtoReflect.Descriptor instead.
func (*GetGoldUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoldUserResponse) GetUsers() []*GoldUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// GetGoldUserByEmailResponse is the response message for GetGoldUserByEmail RPC
type GetGoldUserByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *GoldUser              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoldUserByEmailResponse) Reset() {
	*x = GetGoldUserByEmailResponse{}
	mi := &file_proto_gold_gym_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoldUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoldUserByEmailResponse) ProtoMessage() {}

func (x *GetGoldUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoldUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*GetGoldUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{4}
}

func (x *GetGoldUserByEmailResponse) GetUser() *GoldUser {
	if x != nil {
		return x.User
	}
	return nil
}

// LoginUserRequest is the request message for LoginUser RPC
type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_gold_gym_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{5}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginUserResponse is the response message for LoginUser RPC
type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_proto_gold_gym_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{6}
}

func (x *LoginUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginUserResponse) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *LoginUserResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// InsertGoldUserRequest is the request message for InsertGoldUser RPC
type InsertGoldUserRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GoldEmail             string                 `protobuf:"bytes,1,opt,name=gold_email,json=goldEmail,proto3" json:"gold_email,omitempty"`
	GoldPassword          string                 `protobuf:"bytes,2,opt,name=gold_password,json=goldPassword,proto3" json:"gold_password,omitempty"`
	GoldNama              string                 `protobuf:"bytes,3,opt,name=gold_nama,json=goldNama,proto3" json:"gold_nama,omitempty"`
	GoldNomorhp           string                 `protobuf:"bytes,4,opt,name=gold_nomorhp,json=goldNomorhp,proto3" json:"gold_nomorhp,omitempty"`
	GoldNomorkartu        string                 `protobuf:"bytes,5,opt,name=gold_nomorkartu,json=goldNomorkartu,proto3" json:"gold_nomorkartu,omitempty"`
	GoldCvv               string                 `protobuf:"bytes,6,opt,name=gold_cvv,json=goldCvv,proto3" json:"gold_cvv,omitempty"`
	GoldExpireddate       string                 `protobuf:"bytes,7,opt,name=gold_expireddate,json=goldExpireddate,proto3" json:"gold_expireddate,omitempty"`
	GoldNamapemegangkartu string                 `protobuf:"bytes,8,opt,name=gold_namapemegangkartu,json=goldNamapemegangkartu,proto3" json:"gold_namapemegangkartu,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InsertGoldUserRequest) Reset() {
	*x = InsertGoldUserRequest{}
	mi := &file_proto_gold_gym_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertGoldUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertGoldUserRequest) ProtoMessage() {}

func (x *InsertGoldUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertGoldUserRequest.ProtoReflect.Descriptor instead.
func (*InsertGoldUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{7}
}

func (x *InsertGoldUserRequest) GetGoldEmail() string {
	if x != nil {
		return x.GoldEmail
	}
	return ""
}

func (x *InsertGoldUserRequest) GetGoldPassword() string {
	if x != nil {
		return x.GoldPassword
	}
	return ""
}

func (x *InsertGoldUserRequest) GetGoldNama() string {
	if x != nil {
		return x.GoldNama
	}
	return ""
}

func (x *InsertGoldUserRequest) GetGoldNomorhp() string {
	if x != nil {
		return x.GoldNomorhp
	}
	return ""
}

func (x *InsertGoldUserRequest) GetGoldNomorkartu() string {
	if x != nil {
		return x.GoldNomorkartu
	}
	return ""
}

func (x *InsertGoldUserRequest) GetGoldCvv() string {
	if x != nil {
		return x.GoldCvv
	}
	return ""
}

func (x *InsertGoldUserRequest) GetGoldExpireddate() string {
	if x != nil {
		return x.GoldExpireddate
	}
	return ""
}

func (x *InsertGoldUserRequest) GetGoldNamapemegangkartu() string {
	if x != nil {
		return x.GoldNamapemegangkartu
	}
	return ""
}

// InsertGoldUserResponse is the response message for InsertGoldUser RPC
type InsertGoldUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertGoldUserResponse) Reset() {
	*x = InsertGoldUserResponse{}
	mi := &file_proto_gold_gym_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertGoldUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertGoldUserResponse) ProtoMessage() {}

func (x *InsertGoldUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertGoldUserResponse.ProtoReflect.Descriptor instead.
func (*InsertGoldUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{8}
}

func (x *InsertGoldUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsertGoldUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetAllSubscriptionRequest is the request message for GetAllSubscription RPC
type GetAllSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubscriptionRequest) Reset() {
	*x = GetAllSubscriptionRequest{}
	mi := &file_proto_gold_gym_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubscriptionRequest) ProtoMessage() {}

func (x *GetAllSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetAllSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{9}
}

// Subscription represents a subscription plan
type Subscription struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	GoldNamapaket       string                 `protobuf:"bytes,1,opt,name=gold_namapaket,json=goldNamapaket,proto3" json:"gold_namapaket,omitempty"`
	GoldNamalayanan     string                 `protobuf:"bytes,2,opt,name=gold_namalayanan,json=goldNamalayanan,proto3" json:"gold_namalayanan,omitempty"`
	GoldHarga           float64                `protobuf:"fixed64,3,opt,name=gold_harga,json=goldHarga,proto3" json:"gold_harga,omitempty"`
	GoldJadwal          string                 `protobuf:"bytes,4,opt,name=gold_jadwal,json=goldJadwal,proto3" json:"gold_jadwal,omitempty"`
	GoldListlatihan     string                 `protobuf:"bytes,5,opt,name=gold_listlatihan,json=goldListlatihan,proto3" json:"gold_listlatihan,omitempty"`
	GoldJumlahpertemuan int32                  `protobuf:"varint,6,opt,name=gold_jumlahpertemuan,json=goldJumlahpertemuan,proto3" json:"gold_jumlahpertemuan,omitempty"`
	GoldDurasi          int32                  `protobuf:"varint,7,opt,name=gold_durasi,json=goldDurasi,proto3" json:"gold_durasi,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_gold_gym_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{10}
}

func (x *Subscription) GetGoldNamapaket() string {
	if x != nil {
		return x.GoldNamapaket
	}
	return ""
}

func (x *Subscription) GetGoldNamalayanan() string {
	if x != nil {
		return x.GoldNamalayanan
	}
	return ""
}

func (x *Subscription) GetGoldHarga() float64 {
	if x != nil {
		return x.GoldHarga
	}
	return 0
}

func (x *Subscription) GetGoldJadwal() string {
	if x != nil {
		return x.GoldJadwal
	}
	return ""
}

func (x *Subscription) GetGoldListlatihan() string {
	if x != nil {
		return x.GoldListlatihan
	}
	return ""
}

func (x *Subscription) GetGoldJumlahpertemuan() int32 {
	if x != nil {
		return x.GoldJumlahpertemuan
	}
	return 0
}

func (x *Subscription) GetGoldDurasi() int32 {
	if x != nil {
		return x.GoldDurasi
	}
	return 0
}

// GetAllSubscriptionResponse is the response message for GetAllSubscription RPC
type GetAllSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSubscriptionResponse) Reset() {
	*x = GetAllSubscriptionResponse{}
	mi := &file_proto_gold_gym_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSubscriptionResponse) ProtoMessage() {}

func (x *GetAllSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gold_gym_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetAllSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_gold_gym_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllSubscriptionResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_proto_gold_gym_proto protoreflect.FileDescriptor

const file_proto_gold_gym_proto_rawDesc = "" +
	"\n" +
	"\x14proto/gold_gym.proto\x12\agoldgym\"\x14\n" +
	"\x12GetGoldUserRequest\"1\n" +
	"\x19GetGoldUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xcd\x02\n" +
	"\bGoldUser\x12\x17\n" +
	"\agold_id\x18\x01 \x01(\x05R\x06goldId\x12\x1d\n" +
	"\n" +
	"gold_email\x18\x02 \x01(\tR\tgoldEmail\x12#\n" +
	"\rgold_password\x18\x03 \x01(\tR\fgoldPassword\x12\x1b\n" +
	"\tgold_nama\x18\x04 \x01(\tR\bgoldNama\x12!\n" +
	"\fgold_nomorhp\x18\x05 \x01(\tR\vgoldNomorhp\x12'\n" +
	"\x0fgold_nomorkartu\x18\x06 \x01(\tR\x0egoldNomorkartu\x12\x19\n" +
	"\bgold_cvv\x18\a \x01(\tR\agoldCvv\x12)\n" +
	"\x10gold_expireddate\x18\b \x01(\tR\x0fgoldExpireddate\x125\n" +
	"\x16gold_namapemegangkartu\x18\t \x01(\tR\x15goldNamapemegangkartu\">\n" +
	"\x13GetGoldUserResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.goldgym.GoldUserR\x05users\"C\n" +
	"\x1aGetGoldUserByEmailResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.goldgym.GoldUserR\x04user\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"~\n" +
	"\x11LoginUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\"\xc1\x02\n" +
	"\x15InsertGoldUserRequest\x12\x1d\n" +
	"\n" +
	"gold_email\x18\x01 \x01(\tR\tgoldEmail\x12#\n" +
	"\rgold_password\x18\x02 \x01(\tR\fgoldPassword\x12\x1b\n" +
	"\tgold_nama\x18\x03 \x01(\tR\bgoldNama\x12!\n" +
	"\fgold_nomorhp\x18\x04 \x01(\tR\vgoldNomorhp\x12'\n" +
	"\x0fgold_nomorkartu\x18\x05 \x01(\tR\x0egoldNomorkartu\x12\x19\n" +
	"\bgold_cvv\x18\x06 \x01(\tR\agoldCvv\x12)\n" +
	"\x10gold_expireddate\x18\a \x01(\tR\x0fgoldExpireddate\x125\n" +
	"\x16gold_namapemegangkartu\x18\b \x01(\tR\x15goldNamapemegangkartu\"K\n" +
	"\x16InsertGoldUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1b\n" +
	"\x19GetAllSubscriptionRequest\"\x9f\x02\n" +
	"\fSubscription\x12%\n" +
	"\x0egold_namapaket\x18\x01 \x01(\tR\rgoldNamapaket\x12)\n" +
	"\x10gold_namalayanan\x18\x02 \x01(\tR\x0fgoldNamalayanan\x12\x1d\n" +
	"\n" +
	"gold_harga\x18\x03 \x01(\x01R\tgoldHarga\x12\x1f\n" +
	"\vgold_jadwal\x18\x04 \x01(\tR\n" +
	"goldJadwal\x12)\n" +
	"\x10gold_listlatihan\x18\x05 \x01(\tR\x0fgoldListlatihan\x121\n" +
	"\x14gold_jumlahpertemuan\x18\x06 \x01(\x05R\x13goldJumlahpertemuan\x12\x1f\n" +
	"\vgold_durasi\x18\a \x01(\x05R\n" +
	"goldDurasi\"Y\n" +
	"\x1aGetAllSubscriptionResponse\x12;\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x15.goldgym.SubscriptionR\rsubscriptions2\xaf\x03\n" +
	"\x0eGoldGymService\x12H\n" +
	"\vGetGoldUser\x12\x1b.goldgym.GetGoldUserRequest\x1a\x1c.goldgym.GetGoldUserResponse\x12]\n" +
	"\x12GetGoldUserByEmail\x12\".goldgym.GetGoldUserByEmailRequest\x1a#.goldgym.GetGoldUserByEmailResponse\x12B\n" +
	"\tLoginUser\x12\x19.goldgym.LoginUserRequest\x1a\x1a.goldgym.LoginUserResponse\x12Q\n" +
	"\x0eInsertGoldUser\x12\x1e.goldgym.InsertGoldUserRequest\x1a\x1f.goldgym.InsertGoldUserResponse\x12]\n" +
	"\x12GetAllSubscription\x12\".goldgym.GetAllSubscriptionRequest\x1a#.goldgym.GetAllSubscriptionResponseB\x13Z\x11gold-gym-be/protob\x06proto3"

var (
	file_proto_gold_gym_proto_rawDescOnce sync.Once
	file_proto_gold_gym_proto_rawDescData []byte
)

func file_proto_gold_gym_proto_rawDescGZIP() []byte {
	file_proto_gold_gym_proto_rawDescOnce.Do(func() {
		file_proto_gold_gym_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gold_gym_proto_rawDesc), len(file_proto_gold_gym_proto_rawDesc)))
	})
	return file_proto_gold_gym_proto_rawDescData
}

var file_proto_gold_gym_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_gold_gym_proto_goTypes = []any{
	(*GetGoldUserRequest)(nil),         // 0: goldgym.GetGoldUserRequest
	(*GetGoldUserByEmailRequest)(nil),  // 1: goldgym.GetGoldUserByEmailRequest
	(*GoldUser)(nil),                   // 2: goldgym.GoldUser
	(*GetGoldUserResponse)(nil),        // 3: goldgym.GetGoldUserResponse
	(*GetGoldUserByEmailResponse)(nil), // 4: goldgym.GetGoldUserByEmailResponse
	(*LoginUserRequest)(nil),           // 5: goldgym.LoginUserRequest
	(*LoginUserResponse)(nil),          // 6: goldgym.LoginUserResponse
	(*InsertGoldUserRequest)(nil),      // 7: goldgym.InsertGoldUserRequest
	(*InsertGoldUserResponse)(nil),     // 8: goldgym.InsertGoldUserResponse
	(*GetAllSubscriptionRequest)(nil),  // 9: goldgym.GetAllSubscriptionRequest
	(*Subscription)(nil),               // 10: goldgym.Subscription
	(*GetAllSubscriptionResponse)(nil), // 11: goldgym.GetAllSubscriptionResponse
}
var file_proto_gold_gym_proto_depIdxs = []int32{
	2,  // 0: goldgym.GetGoldUserResponse.users:type_name -> goldgym.GoldUser
	2,  // 1: goldgym.GetGoldUserByEmailResponse.user:type_name -> goldgym.GoldUser
	10, // 2: goldgym.GetAllSubscriptionResponse.subscriptions:type_name -> goldgym.Subscription
	0,  // 3: goldgym.GoldGymService.GetGoldUser:input_type -> goldgym.GetGoldUserRequest
	1,  // 4: goldgym.GoldGymService.GetGoldUserByEmail:input_type -> goldgym.GetGoldUserByEmailRequest
	5,  // 5: goldgym.GoldGymService.LoginUser:input_type -> goldgym.LoginUserRequest
	7,  // 6: goldgym.GoldGymService.InsertGoldUser:input_type -> goldgym.InsertGoldUserRequest
	9,  // 7: goldgym.GoldGymService.GetAllSubscription:input_type -> goldgym.GetAllSubscriptionRequest
	3,  // 8: goldgym.GoldGymService.GetGoldUser:output_type -> goldgym.GetGoldUserResponse
	4,  // 9: goldgym.GoldGymService.GetGoldUserByEmail:output_type -> goldgym.GetGoldUserByEmailResponse
	6,  // 10: goldgym.GoldGymService.LoginUser:output_type -> goldgym.LoginUserResponse
	8,  // 11: goldgym.GoldGymService.InsertGoldUser:output_type -> goldgym.InsertGoldUserResponse
	11, // 12: goldgym.GoldGymService.GetAllSubscription:output_type -> goldgym.GetAllSubscriptionResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_gold_gym_proto_init() }
func file_proto_gold_gym_proto_init() {
	if File_proto_gold_gym_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gold_gym_proto_rawDesc), len(file_proto_gold_gym_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gold_gym_proto_goTypes,
		DependencyIndexes: file_proto_gold_gym_proto_depIdxs,
		MessageInfos:      file_proto_gold_gym_proto_msgTypes,
	}.Build()
	File_proto_gold_gym_proto = out.File
	file_proto_gold_gym_proto_goTypes = nil
	file_proto_gold_gym_proto_depIdxs = nil
}
